name: CI

on:
 push:
   branches:
     - master

jobs:
  build:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s ./test -t ./test
      - name: Send Status Update
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.telegram_chat }}
          token: ${{ secrets.telegram_token }}
          args: ${{ job.status }}
